from scipy.spatial import distance
import numpy as np
r = int(input("Enter the number of rows:")) 
c = int(input("Enter the number of columns:")) 
print("Enter all the elements in row major format with spaces")
inp_elements = list(map(int, input().split())) 
A = np.array(inp_elements).reshape(r, c) 
print("data matrix:")
print(A)
Ecdist = distance.cdist(A, A, 'euclidean')
print("Dussimilarity Matrix(Eucledian distance based)")
print(Ecdist)
Manhdist = distance.cdist(A, A, 'cityblock')
print("Dissimilarity Matrix(Manhattan distance based)")
print(Manhdist)
# hammingdist = distance.cdist(A, A, 'matching')
# print("Dissimilarity Matrix(hamming distance based)")
# print(hammingdist)
Minkdist =  distance.cdist(A, A, 'minkowski', p=2.)
print("Dissimilarity Matrix(Minkowski distance based)")
print(Minkdist)
